namespace: w0
name: xen_orchestra
version: 0.1.0
authors:
  - w0 (https://github.com/w0)
readme: README.md
description: >-
  Ansible collection for managning resources in Xen Orchestra using the rest-api.
license:
  - GPL-3.0-or-later
tags:
  - xen
  - xen_orchestra
  - xcp_ng
  - xpcng
  - virtualization
repository: https://github.com/w0/ansible-xen-orchestra
documentation: https://github.com/w0/ansible-xen-orchestra
homepage: https://github.com/w0/ansible-xen-orchestra
issues: https://github.com/w0/ansible-xen-orchestra/issues

build_ignore:
  - .git
  - .gitignore
  - .venv
  - venv
  - __pycache__
  - "*.pyc"
  - "*.retry"
  - tests/
  - collections/
  - "*.tar.gz"
  - .zed
  - .github
  - pyproject.toml
  - uv.lock
