---
name: Deploy Collection

# Trigger the workflow however you prefer
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get the version name from the tags
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"  # remove 'refs/tags/' prefix
          VERSION="${VERSION#v}"              # remove leading 'v' if it exists
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Injecting a dynamic Collection version
        uses: artis3n/ansible_galaxy_collection@v3
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ env.RELEASE_VERSION }}'
